# Generated by Django 2.2.12 on 2020-07-12 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='номер категории')),
                ('name', models.CharField(max_length=255, verbose_name='название категории')),
                ('icon', models.CharField(max_length=255, verbose_name='значок категории')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='номер уровня')),
                ('name', models.CharField(max_length=255, verbose_name='уровень владения языком')),
                ('code', models.CharField(max_length=2, verbose_name='код уровня владения языком')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='номер темы')),
                ('name', models.CharField(max_length=255, verbose_name='название темы')),
                ('photo', models.CharField(max_length=255, verbose_name='значок темы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='номер слова')),
                ('name', models.CharField(max_length=255, verbose_name='слово')),
                ('translate', models.CharField(max_length=255, verbose_name='перевод')),
                ('transcription', models.CharField(max_length=255, verbose_name='транскрипция')),
                ('example', models.CharField(max_length=255, verbose_name='пример употребления слова')),
                ('sound', models.CharField(max_length=255, verbose_name='произношение слова')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.Theme')),
            ],
        ),
    ]
